name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and package the app
        run: npm run package

      - name: Locate and zip the application
        run: |
          # Check for ARM64 build and zip it
          if [ -d "dist/Deepseek-R1-darwin-arm64/Deepseek-R1.app" ]; then
            echo "Found ARM64 app, zipping..."
            cd dist/Deepseek-R1-darwin-arm64
            zip -r ../../Deepseek-R1-darwin-arm64.zip Deepseek-R1.app
            cd ../..
          else
            echo "ARM64 build directory not found!"
            exit 1
          fi

          # Check for x64 build and zip it
          if [ -d "dist/Deepseek-R1-darwin-x64/Deepseek-R1.app" ]; then
            echo "Found x64 app, zipping..."
            cd dist/Deepseek-R1-darwin-x64
            zip -r ../../Deepseek-R1-darwin-x64.zip Deepseek-R1.app
            cd ../..
          else
            echo "x64 build directory not found!"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Deepseek-R1-Build
          path: |
            deepseek-r1-app-darwin-arm64.zip
            deepseek-r1-app-darwin-x64.zip

      - name: Create Git tag
        id: tag
        run: |
          TAG_NAME="v1.0.$(date +'%s')" 
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Assets (arm64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Deepseek-R1-darwin-arm64.zip
          asset_name: deepseek-r1-app-darwin-arm64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets (x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Deepseek-R1-darwin-x64.zip
          asset_name: deepseek-r1-app-darwin-x64.zip
          asset_content_type: application/zip